### ISSUE TITLE
error cargo build

### ISSUE THREAD

**Issue by hellosct1** [gadomski/rivlib-rs#1]
Hi,

I try to compile the version with the following command line

`cargo build`

`
rivlib-rs$ cargo build
   Compiling scanlib v0.1.0 (/home/portable/wwwRust/rivlib-rs/scanlib)
   Compiling which v1.0.5
The following warnings were emitted during compilation:

warning: src/pointcloud.cpp:1:10: fatal error: riegl/scanlib.hpp: Aucun fichier ou dossier de ce type
warning:     1 | #include <riegl/scanlib.hpp>
warning:       |          ^~~~~~~~~~~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `scanlib v0.1.0 (/home/portable/wwwRust/rivlib-rs/scanlib)`

Caused by:
  process didn't exit successfully: `/home/portable/wwwRust/rivlib-rs/target/debug/build/scanlib-86254ac6486ba308/build-script-build` (exit status: 1)
  --- stdout
  cargo:rustc-link-lib=scanlib-mt
  cargo:rustc-link-lib=riboost_system-mt
  cargo:rustc-link-lib=riboost_filesystem-mt
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-std=c++11" "-o" "/home/portable/wwwRust/rivlib-rs/target/debug/build/scanlib-76478610c9e604f7/out/src/pointcloud.o" "-c" "src/pointcloud.cpp"
  cargo:warning=src/pointcloud.cpp:1:10: fatal error: riegl/scanlib.hpp: Aucun fichier ou dossier de ce type
  cargo:warning=    1 | #include <riegl/scanlib.hpp>
  cargo:warning=      |          ^~~~~~~~~~~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr

  error occurred: Command "c++" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-std=c++11" "-o" "/home/portable/wwwRust/rivlib-rs/target/debug/build/scanlib-76478610c9e604f7/out/src/pointcloud.o" "-c" "src/pointcloud.cpp" with args "c++" did not execute successfully (status code exit status: 1).

warning: build failed, waiting for other jobs to finish...
`

Version : 

* Rustc
rustc 1.63.0 (4b91a6ea7 2022-08-08)

* rivlib version : lasted

thanks

**Comment by gadomski** [comment]
Do you have RiVLib installed on your system and the headers on your search path, per the README? Looks like the header file can't be found.

Closing as non-issue, please re-open if you can confirm your headers _are_ on your search path.
